
# For more information on how to configure this file, please see:
# https://github.com/fishtown-analytics/dbt/blob/master/sample.profiles.yml
config:
    send_anonymous_usage_stats: False
    use_colors: True
    printer_width: 180

default:
  target: integration-local

  outputs:
    integration-local-bigquery:
      type: bigquery
      method: oauth
      project:  "{{ env_var('DBT_PROJECT', 'at-dry-run-integration-dev') }}"
      schema: dry_run
      location: EU
      threads: 8
      timeout_seconds: 300

    integration-github-bigquery:
      type: bigquery
      method: service-account
      project: "{{ env_var('DBT_PROJECT', 'at-dry-run-integration-dev') }}"
      schema: dry_run
      location: EU
      threads: 8
      timeout_seconds: 300
      keyfile: "{{ env_var('HOME', '/home') }}/bq_svc.json"

    integration-local-snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: "{{ env_var('SNOWFLAKE_USERNAME') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"

      database: "{{ env_var('DBT_PROJECT', 'at_dry_run_integration_dev') }}"
      warehouse: COMPUTE_WH
      schema: dry_run
      threads: 8