name: 'test_project_with_snapshots'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
# This will get overridden by the root project
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "logs"


# Configuring models
models:
  # This should match your project name
  test_project_with_snapshots:
    +enabled: true
    +materialized: view