name: Lint and Test

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.13
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Install dependencies
        run: poetry install

      - name: Run linting
        run: make build
